### ISSUE TITLE
pb installation package INCA3

### ISSUE THREAD

**Issue by Pamousse** [ThinkR-open/inca3#2]
Bonjour,

l'installation du package se termine avec le message d'erreur ci-dessous.

Le pb semble venir de l'utilisation d'un chemin bizarre : C:/program files tilichargis/...
Merci par avance pour votre diagnostic.

* remotes::install_github("thinkr-open/inca3", build_vignettes = FALSE)
* Downloading GitHub repo thinkr-open/inca3@master
* Running `R CMD build`...
* checking for file 'C:\Users\Portable Pierre\AppData\Local\Temp\RtmpKEhn25\remotes14dc198c49d1\ThinkR-open-inca3-942a790/DESCRIPTION' ... OK
* preparing 'inca3':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a 'data/datalist' file should be added
* building 'inca3_0.0.1.tar.gz'
* installing *source* package 'inca3' ...
** using staged installation
Error in file(file, if (append) "a" else "w") : 
  (converti depuis l'avis) impossible d'ouvrir le fichier 'C:/program files tilichargis/informatique/R - 141204/R-3.6/R-3.6.0/library/00LOCK-inca3/00new/inca3/DESCRIPTION' : No such file or directory
ERROR: installing package DESCRIPTION failed for package 'inca3'
* removing 'C:/program files téléchargés/informatique/R - 141204/R-3.6/R-3.6.0/library/inca3'
Erreur : Failed to install 'inca3' from GitHub:
  (converti depuis l'avis) installation of package ‘C:/Users/Portable Pierre/AppData/Local/Temp/RtmpKEhn25/file14dc370545d4/inca3_0.0.1.tar.gz’ had non-zero exit status

**Comment by statnmap** [comment]
Ce "chemin bizarre" semble être l'endroit où vous avez choisi d'installer R.  
Les espaces et les caractères spéciaux dans les noms de dossiers et de fichiers sont à proscrire car ils sont souvent très mal ré-encodés dans R, d'autant plus avec Windows.  
Avez-vous déjà réussi à installer un package R en version de développement depuis Github ?
Sinon, il faudra sûrement envisager de changer votre nom d'utilisateur pour qu'il n'y ait pas d'espace et/ou choisir un autre dossier pour installer R, notamment un dossier dont le chemin ne contiendra pas de caractères spéciaux (accents et autres)

**Comment by Pamousse** [comment]
Merci beaucoup pour votre réponse rapide.
C'est la 1ère fois que j'installe un package R depuis Github.
Le chemin "C:/program files tilichargis" n'existe pas sur mon PC. Le chemin utilisé pour installer R apparait d'ailleurs un peu plus bas dans les messages d'erreurs "'C:/program files téléchargés/informatique/...". 
C'est probablement un pb d'encodage. D'habitude, ils sont plus facilement repérables avec le remplacement de caractères accentués par des chaines un peu baroques.
J'avoue que le chemin est effectivement un peu compliqué. Il faudra que je fasse un essai avec une version plus simple / courte au niveau de la racine.
Merci encore

**Comment by statnmap** [comment]
Je suppose qu'il n'y a plus de problème si vous n'êtes pas revenu vers nous.
