### ISSUE TITLE
Utilisation des pondérations dans INCA 3

### ISSUE THREAD

**Issue by mplessz** [ThinkR-open/inca3#9]
Bonjour
Merci beaucoup pour la mise en ligne de ces données.
Comme il est très important de pondérer les données INCA 3, pourriez-vous préciser comment utiliser la pondération dans R, par exemple avec le package `survey`?

En particulier nous nous posons les mêmes questions que celles posées dans un commentaire sur l'ancien site data.gouv.fr  (https://legacy.data.gouv.fr/fr/datasets/donnees-de-consommations-et-habitudes-alimentaires-de-letude-inca-3/)   : 
 1. comment pondérer si on veut travailler sur les individus qui sont à la fois dans pop2 et pop3?
 2. si on veut travailler sur les individus, doit-on inclure `NOMEN` ET `NOIND` dans la déclaration du design?
 
Merci par avance.

**Comment by statnmap** [comment]
Bonjour,
Merci pour votre question.
Nous avons mis à disposition ces données pour pouvoir les utiliser dans nos formations de manipulation et exploration des données avec R.  
Nous ne les avons pas traitées pour des analyses statistiques. Les résultats de nos explorations en formation ne sont pas destinées à être utilisées pour tirer des conclusions.  
De ce fait, nous n'avons malheureusement pas réellement de réponses à vous apporter... 

Peut-être pouvez-vous vous rapprocher des producteurs de données (ANSES) directement ?

**Comment by mplessz** [comment]
Bonjour
Je comprends. pour info voici les réponses que m'a fournies mon interlocutrice à l'ANSES :  
1.  comment pondérer si on veut travailler sur les individus qui sont à la fois dans pop2 et pop3?

> Tout dépend des variables d’intérêt que vous étudiez. Pour travailler sur les consommations, il faut garder uniquement les individus POP3 et prendre la pondération correspondante. Pour les questionnaires, il faut prendre POP2 ou POP1 selon les variables les plus limitantes en effectif et utiliser la pondération correspondante.

2. si on veut travailler sur les individus, doit-on inclure NOMEN ET NOIND dans la déclaration du design?

> Oui car il s’agit du 2ème degré et du 3ème degré de notre plan de sondage : unité géographique, logement, individu. La déclaration du plan de sondage doit suivre les 3 degrés utilisés.

La documentation de l'enquête indique bien qu'il faut pondérer (et traiter séparément les échantillons d'enfants et d'adultes) pour tirer des conclusions.
